# Creating logistic regression model to predict Absenteeism

In [1]:
import numpy as np
import pandas as pd


**Data Load**

In [2]:
raw_csv_data=pd.read_csv("Absenteeism_data (2).csv")

In [3]:
raw_csv_data

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [4]:
df=raw_csv_data.copy()

In [5]:
df

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07/07/2015                     289   
1    36                   0  14/07/2015                     118   
2     3                  23  15/07/2015                     179   
3     7                   7  16/07/2015                     279   
4    11                  23  23/07/2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23/05/2018                     179   
696  28                   6  23/05/2018                     225   
697  18                  10  24/05/2018                     330   
698  25                  23  24/05/2018                     235   
699  15                  28  31/05/2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [6]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [7]:
#display all rows and columns when df is printed
pd.options.display.max_columns=None
pd.options.display.max_rows=None

In [8]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [9]:
df = df.drop(['ID'], axis = 1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [10]:
df_no_age=df.drop(['Age'],axis =1)
df_no_age.head(10)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   
5                  23  10/07/2015                     179                51   
6                  22  17/07/2015                     361                52   
7                  23  24/07/2015                     260                50   
8                  19  06/07/2015                     155                12   
9                  22  13/07/2015                     235                11   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   
5                  239.554               31          1         0     0   
6                  239.554               27          1         1     4   
7                  239.554               23          1         4     0   
8                  239.554               25          1         2     0   
9                  239.554               29          3         1     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  
5                          2  
6                          8  
7                          4  
8                         40  
9                          8

In [11]:
#df['Reason for Absence']

In [12]:
pd.unique(df['Reason for Absence'])
##df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [13]:
len(pd.unique(df['Reason for Absence']))

28

In [14]:
sorted(pd.unique(df['Reason for Absence']))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

**20 is missing**

In [15]:
Reason_dummies=pd.get_dummies(df['Reason for Absence'],drop_first=True)

In [16]:
Reason_dummies.head()

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0  
2   0   0   1   0   0   0   0   0  
3   0   0   0   0   0   0   0   0  
4   0   0   1   0   0   0   0   0

In [17]:
Reason_dummies['check']=Reason_dummies.sum(axis=1)

In [18]:
Reason_dummies.head()

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  22  \
0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   

   23  24  25  26  27  28  check  
0   0   0   0   1   0   0      1  
1   0   0   0   0   0   0      0  
2   1   0   0   0   0   0      1  
3   0   0   0   0   0   0      1  
4   1   0   0   0   0   0      1

In [19]:
Reason_dummies['check'].sum(axis=0)

662

In [20]:
Age_dummies=pd.get_dummies(df['Age'])

In [21]:
Age_dummies.head()

27  28  29  30  31  32  33  34  36  37  38  39  40  41  43  46  47  48  49  \
0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   

   50  58  
0   0   0  
1   1   0  
2   0   0  
3   0   0  
4   0   0

In [22]:
df=df.drop(['Reason for Absence'],axis=1)

In [23]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [24]:
Reason_dummies.loc[:,1:14]

1  2  3  4  5  6  7  8  9  10  11  12  13  14
0    0  0  0  0  0  0  0  0  0   0   0   0   0   0
1    0  0  0  0  0  0  0  0  0   0   0   0   0   0
2    0  0  0  0  0  0  0  0  0   0   0   0   0   0
3    0  0  0  0  0  0  1  0  0   0   0   0   0   0
4    0  0  0  0  0  0  0  0  0   0   0   0   0   0
5    0  0  0  0  0  0  0  0  0   0   0   0   0   0
6    0  0  0  0  0  0  0  0  0   0   0   0   0   0
7    0  0  0  0  0  0  0  0  0   0   0   0   0   0
8    0  0  0  0  0  0  0  0  0   0   0   0   0   0
9    0  0  0  0  0  0  0  0  0   0   0   0   0   0
10   1  0  0  0  0  0  0  0  0   0   0   0   0   0
11   1  0  0  0  0  0  0  0  0   0   0   0   0   0
12   0  0  0  0  0  0  0  0  0   0   1   0   0   0
13   0  0  0  0  0  0  0  0  0   0   1   0   0   0
14   0  0  0  0  0  0  0  0  0   0   0   0   0   0
15   0  0  0  0  0  0  0  0  0   0   0   0   0   1
16   0  0  0  0  0  0  0  0  0   0   0   0   0   0
17   0  0  0  0  0  0  0  0  0   0   0   0   0   0
18   0  0  0  0  0  0  0  0  0   0   1   0   0   0
19   0  0  0  0  0  0  0  0  0   0   0   0   0   0
20   0  0  0  0  0  0  0  0  0   1   0   0   0   0
21   0  0  0  0  0  0  0  0  0   0   1   0   0   0
22   0  0  0  0  0  0  0  0  0   0   0   0   1   0
23   0  0  0  0  0  0  0  0  0   0   0   0   0   0
24   0  0  0  0  0  0  0  0  0   0   0   0   0   0
25   0  0  0  0  0  0  0  0  0   0   0   0   0   0
26   0  0  0  0  0  0  0  0  0   0   0   0   0   0
27   0  0  0  0  0  0  0  0  0   0   0   0   0   0
28   0  0  0  0  0  0  0  0  0   0   0   0   0   0
29   0  0  0  0  0  0  0  0  0   0   0   0   0   0
30   0  0  0  0  0  0  0  0  0   0   0   0   0   0
31   0  0  0  0  0  0  0  0  0   0   0   0   0   0
32   0  0  0  0  0  0  0  0  0   0   0   0   0   0
33   0  0  0  0  0  0  0  0  0   0   0   0   0   0
34   0  0  0  0  0  0  0  0  0   0   0   0   0   0
35   0  0  0  0  0  0  0  0  0   0   0   0   0   0
36   0  0  0  0  0  0  0  0  0   0   0   0   0   0
37   0  0  0  0  0  0  0  0  0   0   1   0   0   0
38   0  0  0  0  0  0  0  0  0   0   0   0   0   0
39   0  0  0  0  0  0  0  0  0   0   0   0   0   0
40   0  0  0  0  0  0  0  0  0   0   0   0   0   0
41   0  0  0  0  0  0  0  0  0   0   0   0   0   0
42   0  0  0  0  0  0  0  0  0   0   0   0   0   0
43   0  0  0  0  0  0  0  0  0   0   0   0   0   0
44   0  0  0  0  0  0  0  0  0   0   0   0   0   0
45   0  0  0  0  0  0  0  0  0   0   0   0   0   0
46   0  0  0  0  0  0  0  0  0   0   0   0   0   0
47   0  0  0  0  0  0  0  0  0   0   0   0   0   0
48   0  0  0  0  0  0  0  0  0   0   0   0   0   0
49   0  0  0  0  0  0  0  0  0   0   0   0   0   1
50   0  0  0  0  0  0  0  0  0   0   0   0   0   0
51   0  0  0  0  0  0  0  0  0   0   0   0   0   0
52   0  0  0  0  0  0  0  0  0   0   0   0   0   0
53   0  0  0  0  0  0  0  0  0   0   0   0   0   0
54   0  0  0  0  0  0  0  0  0   0   0   0   0   0
55   0  0  0  0  0  0  0  0  0   0   0   0   0   0
56   0  0  0  0  0  0  0  0  0   0   0   0   0   0
57   0  0  0  0  0  0  0  0  0   0   0   0   0   0
58   0  0  0  0  0  0  0  0  0   0   0   0   0   0
59   0  0  0  0  0  0  0  0  0   0   0   0   0   0
60   0  0  0  0  0  0  0  0  0   0   0   0   0   0
61   0  0  0  0  0  0  0  0  0   0   0   0   0   0
62   0  0  0  0  0  0  0  0  0   0   0   0   0   0
63   0  0  0  0  0  0  0  0  0   0   0   0   0   0
64   0  0  0  0  0  0  0  0  0   0   0   0   0   0
65   0  0  0  0  0  0  0  0  0   0   0   0   0   0
66   0  0  0  0  0  0  0  0  0   0   0   0   0   0
67   0  0  0  0  0  0  0  0  0   0   0   0   0   0
68   0  0  0  0  0  0  0  0  0   0   0   0   0   0
69   0  0  0  0  0  0  0  0  0   0   0   0   0   0
70   0  0  0  0  0  0  0  0  0   0   0   0   0   0
71   0  0  0  0  0  0  0  0  0   0   0   0   0   0
72   0  0  0  0  0  0  0  0  0   0   0   0   0   0
73   0  0  0  0  0  0  0  0  0   0   0   0   0   0
74   0  0  0  0  0  0  0  0  0   0   0   0   0   0
75   0  0  0  0  0  0  0  0  0   0   0   0   0   1
76   0  0  0  0  0  0  0  0  0   0   0   0   0   0
77   0  0  0  0  0  0  0  0

In [25]:
reason_type_1=Reason_dummies.loc[:,1:14].max(axis=1)
reason_type_2=Reason_dummies.loc[:,15:17].max(axis=1)
reason_type_3=Reason_dummies.loc[:,18:22].max(axis=1)
reason_type_4=Reason_dummies.loc[:,22:].max(axis=1)

In [26]:
reason_type_1

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [27]:
df.head(10)

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   
5  10/07/2015                     179                51   38   
6  17/07/2015                     361                52   28   
7  24/07/2015                     260                50   36   
8  06/07/2015                     155                12   34   
9  13/07/2015                     235                11   37   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   
5                  239.554               31          1         0     0   
6                  239.554               27          1         1     4   
7                  239.554               23          1         4     0   
8                  239.554               25          1         2     0   
9                  239.554               29          3         1     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  
5                          2  
6                          8  
7                          4  
8                         40  
9                          8

In [28]:
df=pd.concat([df,reason_type_1,reason_type_2,reason_type_3,reason_type_4],axis=1)

In [29]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  1  
4                          2  0  0  0  1

In [30]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [31]:
column_names=['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1','Reason_2','Reason_3','Reason_4']

In [32]:
df.columns=column_names
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         1  
4                          2         0         0         0         1

In [33]:
df_reason_mod=df.copy()

In [34]:
type(df_reason_mod['Date'][0])

str

In [35]:
df_reason_mod['Date']=pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [36]:
#df_reason_mod['Date']

0     2015-07-07
1     2015-07-14
2     2015-07-15
3     2015-07-16
4     2015-07-23
5     2015-07-10
6     2015-07-17
7     2015-07-24
8     2015-07-06
9     2015-07-13
10    2015-07-20
11    2015-07-14
12    2015-07-15
13    2015-07-15
14    2015-07-15
15    2015-07-17
16    2015-07-17
17    2015-07-27
18    2015-07-30
19    2015-08-05
20    2015-08-12
21    2015-08-03
22    2015-08-10
23    2015-08-14
24    2015-08-17
25    2015-08-24
26    2015-08-04
27    2015-08-12
28    2015-08-19
29    2015-08-28
30    2015-08-17
31    2015-08-27
32    2015-08-27
33    2015-08-17
34    2015-08-17
35    2015-08-17
36    2015-08-04
37    2015-08-20
38    2015-08-21
39    2015-08-28
40    2015-09-01
41    2015-09-07
42    2015-09-01
43    2015-09-08
44    2015-09-09
45    2015-09-13
46    2015-09-14
47    2015-09-24
48    2015-09-04
49    2015-09-14
50    2015-09-21
51    2015-09-28
52    2015-09-08
53    2015-09-15
54    2015-09-22
55    2015-09-29
56    2015-09-16
57    2015-09-23
58    2015-09-

# Extract the month

In [37]:
list_months=[]
list_months

[]

In [38]:
for i in range(700):
    list_months.append(df_reason_mod['Date'][i].month)

In [39]:
#list_months

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 

In [40]:
len(list_months)

700

In [41]:
df_reason_mod['Month_value']=list_months

In [42]:
df_reason_mod.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  \
0                          4         0         0         0         1   
1                          0         0         0         0         0   
2                          2         0         0         0         1   
3                          4         1         0         0         1   
4                          2         0         0         0         1   

   Month_value  
0            7  
1            7  
2            7  
3            7  
4            7

In [43]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [44]:
df_reason_mod['Day of the week']=df_reason_mod['Date'].apply(date_to_weekday)

In [45]:
df_reason_mod['Day of the week'][0]

1

In [46]:
df_reason_mod.head()

Date  Transportation Expense  Distance to Work  Age  \
0 2015-07-07                     289                36   33   
1 2015-07-14                     118                13   50   
2 2015-07-15                     179                51   38   
3 2015-07-16                     279                 5   39   
4 2015-07-23                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  \
0                          4         0         0         0         1   
1                          0         0         0         0         0   
2                          2         0         0         0         1   
3                          4         1         0         0         1   
4                          2         0         0         0         1   

   Month_value  Day of the week  
0            7                1  
1            7                1  
2            7                2  
3            7                3  
4            7                3

In [47]:
df_reason_mod = df_reason_mod.drop(['Date'], axis = 1)
df_reason_mod.head()

Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          1         2     1                          4   
1               31          1         1     0                          0   
2               31          1         0     0                          2   
3               24          1         2     0                          4   
4               30          1         2     1                          2   

   Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the week  
0         0         0         0         1            7                1  
1         0         0         0         0            7                1  
2         0         0         0         1            7                2  
3         1         0         0         1            7                3  
4         0         0         0         1            7                3

In [48]:
column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_value', 'Day of the week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

In [49]:
df_reason_mod = df_reason_mod[column_names_upd]
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         1            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [50]:
df_reason_date_mod=df_reason_mod.copy()

In [100]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         1            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [52]:
type(df_reason_date_mod['Transportation Expense'][0])
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [53]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [54]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [55]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [56]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

In [57]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [58]:
df_reason_date_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [59]:
df_reason_date_mod['Education']=df_reason_date_mod['Education'].map({1:0,2:1,3:1,4:1})

In [60]:
df_reason_date_mod['Education'].unique()

array([0, 1], dtype=int64)

In [61]:
df_reason_date_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

## Final checkpoint of preprocessed data

In [62]:
df_preprocessed=df_reason_date_mod.copy()

In [63]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         1            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [64]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [65]:
## we took the median as the cut off line 
## median obtained is 3.0 which means someone who is absent for more than 3 hours in a week is considered as excessive  absent

In [66]:
targets=np.where(df_preprocessed['Absenteeism Time in Hours']> df_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [67]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [68]:
df_preprocessed['Excessive Absenteeism']=targets

In [69]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         1            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [70]:
targets.sum() / targets.shape[0]
#checking whether the dataset is balanced or not
#Its almost balanced (45%-55%)

0.45571428571428574

In [71]:
data_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours','Day of the week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [72]:
data_with_targets is df_preprocessed

False

In [73]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         1            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [74]:
data_with_targets.shape

(700, 12)

## Scaling

In [75]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [76]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler=StandardScaler()
#define scaler as an object

In [77]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [78]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [81]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [82]:
reg=LogisticRegression()

In [83]:
reg.fit(x_train, y_train)

LogisticRegression()

In [84]:
reg.score(x_test,y_test)

0.7714285714285715

In [85]:
model_output=reg.predict(x_train)

In [86]:
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [87]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [88]:
model_output==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [89]:
np.sum(model_output==y_train)

451

In [90]:
model_output.shape[0]

560

In [91]:
np.sum(model_output==y_train)/model_output.shape[0]
#manually we got different score because in manual claculation we have flipped the order

0.8053571428571429

In [92]:
reg.score(x_test,y_test)

0.7714285714285715

In [93]:
predicted_proba=reg.predict_proba(x_test)

In [94]:
predicted_proba

array([[0.69210698, 0.30789302],
       [0.62219303, 0.37780697],
       [0.39954588, 0.60045412],
       [0.80338878, 0.19661122],
       [0.06197556, 0.93802444],
       [0.28623299, 0.71376701],
       [0.32289805, 0.67710195],
       [0.06600394, 0.93399606],
       [0.86900769, 0.13099231],
       [0.7519052 , 0.2480948 ],
       [0.06160261, 0.93839739],
       [0.00991149, 0.99008851],
       [0.02868443, 0.97131557],
       [0.15750718, 0.84249282],
       [0.19183318, 0.80816682],
       [0.6268459 , 0.3731541 ],
       [0.7312109 , 0.2687891 ],
       [0.08131161, 0.91868839],
       [0.43551921, 0.56448079],
       [0.01880638, 0.98119362],
       [0.75863041, 0.24136959],
       [0.80338878, 0.19661122],
       [0.32795294, 0.67204706],
       [0.32795294, 0.67204706],
       [0.15674815, 0.84325185],
       [0.82034688, 0.17965312],
       [0.51279511, 0.48720489],
       [0.89553793, 0.10446207],
       [0.07305091, 0.92694909],
       [0.80338878, 0.19661122],
       [0.

In [95]:
predicted_proba.shape

(140, 2)

In [96]:
predicted_proba[:,1]
#select only the probabilities referring to 1

array([0.30789302, 0.37780697, 0.60045412, 0.19661122, 0.93802444,
       0.71376701, 0.67710195, 0.93399606, 0.13099231, 0.2480948 ,
       0.93839739, 0.99008851, 0.97131557, 0.84249282, 0.80816682,
       0.3731541 , 0.2687891 , 0.91868839, 0.56448079, 0.98119362,
       0.24136959, 0.19661122, 0.67204706, 0.67204706, 0.84325185,
       0.17965312, 0.48720489, 0.10446207, 0.92694909, 0.19661122,
       0.92777829, 0.64073443, 0.74329321, 0.94648914, 0.19661122,
       0.96111725, 0.13973286, 0.86470118, 0.33159665, 0.59764809,
       0.18507827, 0.39535392, 0.158677  , 0.01290197, 0.83774381,
       0.75936572, 0.72610195, 0.30789302, 0.19342616, 0.17407524,
       0.59793512, 0.00875919, 0.71376701, 0.27295471, 0.86086511,
       0.41351303, 0.90680663, 0.19448461, 0.0112607 , 0.01212353,
       0.69149742, 0.6982646 , 0.28941854, 0.88656649, 0.12407549,
       0.27699959, 0.00200389, 0.13973286, 0.87245375, 0.8782226 ,
       0.13973286, 0.00802375, 0.94286043, 0.41885913, 0.57567

## save the model

In [97]:
import pickle

In [98]:
with open('model','wb') as file:
    pickle.dump(reg, file)

In [99]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)